apiVersion: v1
kind: Pod
metadata:
  name: nginx-slowboot
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    command: ["/bin/sh"]
    args: ["-c", "sleep 120; nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-quickboot
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-quickboot
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
