apiVersion: v1
kind: Pod
metadata:
  name: nginx-slowboot
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    
    command: ["/bin/sh"]
    args: ["-c", "sleep 60; nginx -g 'daemon off;'"]
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 20
      periodSeconds: 20
